stages:
  - test
  - deploy

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "Code coverage is 90%"

lint-test-job:
  stage: deploy
  script:
    - echo "Linting code... This will take about 10 seconds."
    - echo "No lint issues found."
